export const PERMISSION_CODE = {
  V1_WORKTEAM_LIST: '/api/v1/workteam/list',
  V1_WORKTEAM_GET: '/api/v1/workteam/get',
  V1_URLRESOURCE_LIST: '/api/v1/urlresource/list',
  V1_RTDATAMOVINGSITE_LIST: '/api/v1/rtdatamovingsite/list',
  V1_RTDATAFIXEDSITE_LIST: '/api/v1/rtdatafixedsite/list',
  V1_ROLE_UPDATE: '/api/v1/role/update',
  V1_ROLE_LIST: '/api/v1/role/list',
  V1_ROLE_GET: '/api/v1/role/get',
  V1_ROLE_DELETE: '/api/v1/role/delete',
  V1_ROLE_ADD: '/api/v1/role/add',
  V1_REGIONRESOURCE_LIST: '/api/v1/regionresource/list',
  V1_REGION_LIST: '/api/v1/region/list',
  V1_MOVINGSITE_LIST: '/api/v1/movingsite/list',
  V1_MOVINGSITE_GET: '/api/v1/movingsite/get',
  V1_LOGOUT: '/api/v1/logout',
  V1_LOGIN: '/api/v1/login',
  V1_LOADFIXEDSITE_LIST: '/api/v1/loadfixedsite/list',
  V1_FIXEDSITE_LIST: '/api/v1/fixedsite/list',
  V1_FIXEDSITE_GET: '/api/v1/fixedsite/get',
  V1_EVENTMOVINGSITE_UPDATE: '/api/v1/eventmovingsite/update',
  V1_EVENTMOVINGSITE_LIST: '/api/v1/eventmovingsite/list',
  V1_EVENTFIXEDSITE_UPDATE: '/api/v1/eventfixedsite/update',
  V1_EVENTFIXEDSITE_LIST: '/api/v1/eventfixedsite/list',
  V1_EMPLOYEE_LIST: '/api/v1/employee/list',
  V1_EMPLOYEE_GET: '/api/v1/employee/get',
  V1_CVTMOVINGSITE_UPDATE: '/api/v1/cvtmovingsite/update',
  V1_CVTMOVINGSITE_LIST: '/api/v1/cvtmovingsite/list',
  V1_CVTFIXEDSITE_UPDATE: '/api/v1/cvtfixedsite/update',
  V1_CVTFIXEDSITE_LIST: '/api/v1/cvtfixedsite/list',
  V1_CONTROLMOVINGSITE_LIST: '/api/v1/controlmovingsite/list',
  V1_CONTROLMOVINGSITE_ADD: '/api/v1/controlmovingsite/add',
  V1_CONTROLFIXEDSITE_LIST: '/api/v1/controlfixedsite/list',
  V1_CONTROLFIXEDSITE_ADD: '/api/v1/controlfixedsite/add',
  V1_BIND_LIST: '/api/v1/bind/list',
  V1_BIND_DELETE: '/api/v1/bind/delete',
  V1_BIND_ADD: '/api/v1/bind/add',
} as const;

export const PERMISSION_MAP = {
  [PERMISSION_CODE.V1_WORKTEAM_LIST]: { label: '获取作业大队登记列表' },
  [PERMISSION_CODE.V1_WORKTEAM_GET]: { label: '获取作业大队详细信息' },
  [PERMISSION_CODE.V1_URLRESOURCE_LIST]: { label: '获取Url资源列表' },
  [PERMISSION_CODE.V1_RTDATAMOVINGSITE_LIST]: { label: '获取车辆位置记录列表' },
  [PERMISSION_CODE.V1_RTDATAFIXEDSITE_LIST]: { label: '获取站点罐液位+温度历史数据记录列表' },
  [PERMISSION_CODE.V1_ROLE_UPDATE]: { label: '更新Role' },
  [PERMISSION_CODE.V1_ROLE_LIST]: { label: 'Role列表' },
  [PERMISSION_CODE.V1_ROLE_GET]: { label: '获取Role' },
  [PERMISSION_CODE.V1_ROLE_DELETE]: { label: '删除Role' },
  [PERMISSION_CODE.V1_ROLE_ADD]: { label: '添加Role' },
  [PERMISSION_CODE.V1_REGIONRESOURCE_LIST]: { label: '获取站点区域列表' },
  [PERMISSION_CODE.V1_REGION_LIST]: { label: '获取工区列表' },
  [PERMISSION_CODE.V1_MOVINGSITE_LIST]: { label: '获取车辆列表' },
  [PERMISSION_CODE.V1_MOVINGSITE_GET]: { label: '获取车辆详细信息' },
  [PERMISSION_CODE.V1_LOGOUT]: { label: '注销' },
  [PERMISSION_CODE.V1_LOGIN]: { label: '登录' },
  [PERMISSION_CODE.V1_LOADFIXEDSITE_LIST]: { label: '获取装车记录列表' },
  [PERMISSION_CODE.V1_FIXEDSITE_LIST]: { label: '获取站点列表' },
  [PERMISSION_CODE.V1_FIXEDSITE_GET]: { label: '获取站点详细信息' },
  [PERMISSION_CODE.V1_EVENTMOVINGSITE_UPDATE]: { label: '更新车辆事件' },
  [PERMISSION_CODE.V1_EVENTMOVINGSITE_LIST]: { label: '获取车辆事件（含报警）记录列表' },
  [PERMISSION_CODE.V1_EVENTFIXEDSITE_UPDATE]: { label: '更新站点事件' },
  [PERMISSION_CODE.V1_EVENTFIXEDSITE_LIST]: { label: '获取站点事件（含报警）记录列表' },
  [PERMISSION_CODE.V1_EMPLOYEE_LIST]: { label: '获取人员列表' },
  [PERMISSION_CODE.V1_EMPLOYEE_GET]: { label: '获取人员详细信息' },
  [PERMISSION_CODE.V1_CVTMOVINGSITE_UPDATE]: { label: '更新车辆当前值' },
  [PERMISSION_CODE.V1_CVTMOVINGSITE_LIST]: { label: '获取车辆当前值列表' },
  [PERMISSION_CODE.V1_CVTFIXEDSITE_UPDATE]: { label: '更新站点当前值' },
  [PERMISSION_CODE.V1_CVTFIXEDSITE_LIST]: { label: '获取站点当前值列表' },
  [PERMISSION_CODE.V1_CONTROLMOVINGSITE_LIST]: { label: '获取下发车辆指令列表' },
  [PERMISSION_CODE.V1_CONTROLMOVINGSITE_ADD]: { label: '添加移动站点指令' },
  [PERMISSION_CODE.V1_CONTROLFIXEDSITE_LIST]: { label: '获取下发站点指令列表' },
  [PERMISSION_CODE.V1_CONTROLFIXEDSITE_ADD]: { label: '添加固定站点指令' },
  [PERMISSION_CODE.V1_BIND_LIST]: { label: 'Bind列表' },
  [PERMISSION_CODE.V1_BIND_DELETE]: { label: '删除Bind' },
  [PERMISSION_CODE.V1_BIND_ADD]: { label: '添加Bind' },
} as const;
